-- BSconta+ RH — carga inicial dos colaboradores importados da Empregados.xls
-- A planilha fornecida possui 15 empregados e não contém e-mails; os e-mails
-- abaixo são provisórios e devem ser substituídos pelos e-mails corporativos reais.
-- Esta carga usa uma tabela de staging independente do auth.users para permitir
-- importação imediata. O vínculo com profiles/auth.users ocorre na implantação.

create table if not exists public.colaboradores_importacao (
  id text primary key,
  nome text not null,
  email text not null,
  codigo_colaborador text not null unique,
  cargo text,
  departamento text,
  admissao date,
  status text not null default 'ATIVO',
  email_provisorio boolean not null default true,
  horario_entrada time,
  horario_saida time,
  intervalo_inicio time,
  intervalo_fim time,
  dias_trabalho text[] not null default '{}',
  horas_semanais numeric,
  fonte_cadastro text,
  observacao_email text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

insert into public.colaboradores_importacao (id,nome,email,codigo_colaborador,cargo,departamento,admissao,status,email_provisorio,horario_entrada,horario_saida,intervalo_inicio,intervalo_fim,dias_trabalho,horas_semanais,fonte_cadastro,observacao_email) values ('EMP-012','Angella dos Santos Gomes','angella.dos.santos.gomes@bsconta.com.br','BSconta+12','Assistente Fiscal/Contabil','Fiscal/Contábil',NULL,'ATIVO',true,NULL,NULL,NULL,NULL,'{}'::text[],NULL,'Empregados.xls','E-mail não consta na planilha; valor provisório para funcionamento do protótipo.') on conflict (id) do update set nome=excluded.nome,email=excluded.email,codigo_colaborador=excluded.codigo_colaborador,cargo=excluded.cargo,departamento=excluded.departamento,admissao=excluded.admissao,status=excluded.status,email_provisorio=excluded.email_provisorio,horario_entrada=excluded.horario_entrada,horario_saida=excluded.horario_saida,intervalo_inicio=excluded.intervalo_inicio,intervalo_fim=excluded.intervalo_fim,dias_trabalho=excluded.dias_trabalho,horas_semanais=excluded.horas_semanais,fonte_cadastro=excluded.fonte_cadastro,observacao_email=excluded.observacao_email,updated_at=now();
insert into public.colaboradores_importacao (id,nome,email,codigo_colaborador,cargo,departamento,admissao,status,email_provisorio,horario_entrada,horario_saida,intervalo_inicio,intervalo_fim,dias_trabalho,horas_semanais,fonte_cadastro,observacao_email) values ('EMP-013','ARTHUR PONTIL SCALA','arthur.pontil.scala@bsconta.com.br','BSconta+13','Analista de Departamento Pessoal','Departamento Pessoal',NULL,'ATIVO',true,NULL,NULL,NULL,NULL,'{}'::text[],NULL,'Empregados.xls','E-mail não consta na planilha; valor provisório para funcionamento do protótipo.') on conflict (id) do update set nome=excluded.nome,email=excluded.email,codigo_colaborador=excluded.codigo_colaborador,cargo=excluded.cargo,departamento=excluded.departamento,admissao=excluded.admissao,status=excluded.status,email_provisorio=excluded.email_provisorio,horario_entrada=excluded.horario_entrada,horario_saida=excluded.horario_saida,intervalo_inicio=excluded.intervalo_inicio,intervalo_fim=excluded.intervalo_fim,dias_trabalho=excluded.dias_trabalho,horas_semanais=excluded.horas_semanais,fonte_cadastro=excluded.fonte_cadastro,observacao_email=excluded.observacao_email,updated_at=now();
insert into public.colaboradores_importacao (id,nome,email,codigo_colaborador,cargo,departamento,admissao,status,email_provisorio,horario_entrada,horario_saida,intervalo_inicio,intervalo_fim,dias_trabalho,horas_semanais,fonte_cadastro,observacao_email) values ('EMP-014','FERNANDO SOARES BAETA','fernando.soares.baeta@bsconta.com.br','BSconta+14','Analista Contabil I','Contábil',NULL,'ATIVO',true,NULL,NULL,NULL,NULL,'{}'::text[],NULL,'Empregados.xls','E-mail não consta na planilha; valor provisório para funcionamento do protótipo.') on conflict (id) do update set nome=excluded.nome,email=excluded.email,codigo_colaborador=excluded.codigo_colaborador,cargo=excluded.cargo,departamento=excluded.departamento,admissao=excluded.admissao,status=excluded.status,email_provisorio=excluded.email_provisorio,horario_entrada=excluded.horario_entrada,horario_saida=excluded.horario_saida,intervalo_inicio=excluded.intervalo_inicio,intervalo_fim=excluded.intervalo_fim,dias_trabalho=excluded.dias_trabalho,horas_semanais=excluded.horas_semanais,fonte_cadastro=excluded.fonte_cadastro,observacao_email=excluded.observacao_email,updated_at=now();
insert into public.colaboradores_importacao (id,nome,email,codigo_colaborador,cargo,departamento,admissao,status,email_provisorio,horario_entrada,horario_saida,intervalo_inicio,intervalo_fim,dias_trabalho,horas_semanais,fonte_cadastro,observacao_email) values ('EMP-015','Iara Cristina Silva Andrade','iara.cristina.silva.andrade@bsconta.com.br','BSconta+15','Assistente Fiscal/Contabil','Fiscal/Contábil',NULL,'ATIVO',true,NULL,NULL,NULL,NULL,'{}'::text[],NULL,'Empregados.xls','E-mail não consta na planilha; valor provisório para funcionamento do protótipo.') on conflict (id) do update set nome=excluded.nome,email=excluded.email,codigo_colaborador=excluded.codigo_colaborador,cargo=excluded.cargo,departamento=excluded.departamento,admissao=excluded.admissao,status=excluded.status,email_provisorio=excluded.email_provisorio,horario_entrada=excluded.horario_entrada,horario_saida=excluded.horario_saida,intervalo_inicio=excluded.intervalo_inicio,intervalo_fim=excluded.intervalo_fim,dias_trabalho=excluded.dias_trabalho,horas_semanais=excluded.horas_semanais,fonte_cadastro=excluded.fonte_cadastro,observacao_email=excluded.observacao_email,updated_at=now();
insert into public.colaboradores_importacao (id,nome,email,codigo_colaborador,cargo,departamento,admissao,status,email_provisorio,horario_entrada,horario_saida,intervalo_inicio,intervalo_fim,dias_trabalho,horas_semanais,fonte_cadastro,observacao_email) values ('EMP-016','JOAO PEDRO FERNANDES DE JESUS','joao.pedro.fernandes.de.jesus@bsconta.com.br','BSconta+16','Assistente Fiscal/Contabil I','Fiscal/Contábil',NULL,'ATIVO',true,NULL,NULL,NULL,NULL,'{}'::text[],NULL,'Empregados.xls','E-mail não consta na planilha; valor provisório para funcionamento do protótipo.') on conflict (id) do update set nome=excluded.nome,email=excluded.email,codigo_colaborador=excluded.codigo_colaborador,cargo=excluded.cargo,departamento=excluded.departamento,admissao=excluded.admissao,status=excluded.status,email_provisorio=excluded.email_provisorio,horario_entrada=excluded.horario_entrada,horario_saida=excluded.horario_saida,intervalo_inicio=excluded.intervalo_inicio,intervalo_fim=excluded.intervalo_fim,dias_trabalho=excluded.dias_trabalho,horas_semanais=excluded.horas_semanais,fonte_cadastro=excluded.fonte_cadastro,observacao_email=excluded.observacao_email,updated_at=now();
insert into public.colaboradores_importacao (id,nome,email,codigo_colaborador,cargo,departamento,admissao,status,email_provisorio,horario_entrada,horario_saida,intervalo_inicio,intervalo_fim,dias_trabalho,horas_semanais,fonte_cadastro,observacao_email) values ('EMP-017','LAYSLA MARIA BESSA FERNANDES SILVA','laysla.maria.bessa.fernandes.silva@bsconta.com.br','BSconta+17','Auxiliar de Contabilidade','Contábil',NULL,'ATIVO',true,NULL,NULL,NULL,NULL,'{}'::text[],NULL,'Empregados.xls','E-mail não consta na planilha; valor provisório para funcionamento do protótipo.') on conflict (id) do update set nome=excluded.nome,email=excluded.email,codigo_colaborador=excluded.codigo_colaborador,cargo=excluded.cargo,departamento=excluded.departamento,admissao=excluded.admissao,status=excluded.status,email_provisorio=excluded.email_provisorio,horario_entrada=excluded.horario_entrada,horario_saida=excluded.horario_saida,intervalo_inicio=excluded.intervalo_inicio,intervalo_fim=excluded.intervalo_fim,dias_trabalho=excluded.dias_trabalho,horas_semanais=excluded.horas_semanais,fonte_cadastro=excluded.fonte_cadastro,observacao_email=excluded.observacao_email,updated_at=now();
insert into public.colaboradores_importacao (id,nome,email,codigo_colaborador,cargo,departamento,admissao,status,email_provisorio,horario_entrada,horario_saida,intervalo_inicio,intervalo_fim,dias_trabalho,horas_semanais,fonte_cadastro,observacao_email) values ('EMP-018','Livia Cristina Freitas de Paula Soares','livia.cristina.freitas.de.paula.soares@bsconta.com.br','BSconta+18','Analista de Departamento Pessoal I','Departamento Pessoal',NULL,'ATIVO',true,NULL,NULL,NULL,NULL,'{}'::text[],NULL,'Empregados.xls','E-mail não consta na planilha; valor provisório para funcionamento do protótipo.') on conflict (id) do update set nome=excluded.nome,email=excluded.email,codigo_colaborador=excluded.codigo_colaborador,cargo=excluded.cargo,departamento=excluded.departamento,admissao=excluded.admissao,status=excluded.status,email_provisorio=excluded.email_provisorio,horario_entrada=excluded.horario_entrada,horario_saida=excluded.horario_saida,intervalo_inicio=excluded.intervalo_inicio,intervalo_fim=excluded.intervalo_fim,dias_trabalho=excluded.dias_trabalho,horas_semanais=excluded.horas_semanais,fonte_cadastro=excluded.fonte_cadastro,observacao_email=excluded.observacao_email,updated_at=now();
insert into public.colaboradores_importacao (id,nome,email,codigo_colaborador,cargo,departamento,admissao,status,email_provisorio,horario_entrada,horario_saida,intervalo_inicio,intervalo_fim,dias_trabalho,horas_semanais,fonte_cadastro,observacao_email) values ('EMP-019','LORENA VIEIRA DE SELES','lorena.vieira.de.seles@bsconta.com.br','BSconta+19','Assistente de Departamento Pessoal','Departamento Pessoal',NULL,'ATIVO',true,NULL,NULL,NULL,NULL,'{}'::text[],NULL,'Empregados.xls','E-mail não consta na planilha; valor provisório para funcionamento do protótipo.') on conflict (id) do update set nome=excluded.nome,email=excluded.email,codigo_colaborador=excluded.codigo_colaborador,cargo=excluded.cargo,departamento=excluded.departamento,admissao=excluded.admissao,status=excluded.status,email_provisorio=excluded.email_provisorio,horario_entrada=excluded.horario_entrada,horario_saida=excluded.horario_saida,intervalo_inicio=excluded.intervalo_inicio,intervalo_fim=excluded.intervalo_fim,dias_trabalho=excluded.dias_trabalho,horas_semanais=excluded.horas_semanais,fonte_cadastro=excluded.fonte_cadastro,observacao_email=excluded.observacao_email,updated_at=now();
insert into public.colaboradores_importacao (id,nome,email,codigo_colaborador,cargo,departamento,admissao,status,email_provisorio,horario_entrada,horario_saida,intervalo_inicio,intervalo_fim,dias_trabalho,horas_semanais,fonte_cadastro,observacao_email) values ('EMP-020','Ludilene dos Santos Lima','ludilene.dos.santos.lima@bsconta.com.br','BSconta+20','Analista Fiscal I','Fiscal',NULL,'ATIVO',true,NULL,NULL,NULL,NULL,'{}'::text[],NULL,'Empregados.xls','E-mail não consta na planilha; valor provisório para funcionamento do protótipo.') on conflict (id) do update set nome=excluded.nome,email=excluded.email,codigo_colaborador=excluded.codigo_colaborador,cargo=excluded.cargo,departamento=excluded.departamento,admissao=excluded.admissao,status=excluded.status,email_provisorio=excluded.email_provisorio,horario_entrada=excluded.horario_entrada,horario_saida=excluded.horario_saida,intervalo_inicio=excluded.intervalo_inicio,intervalo_fim=excluded.intervalo_fim,dias_trabalho=excluded.dias_trabalho,horas_semanais=excluded.horas_semanais,fonte_cadastro=excluded.fonte_cadastro,observacao_email=excluded.observacao_email,updated_at=now();
insert into public.colaboradores_importacao (id,nome,email,codigo_colaborador,cargo,departamento,admissao,status,email_provisorio,horario_entrada,horario_saida,intervalo_inicio,intervalo_fim,dias_trabalho,horas_semanais,fonte_cadastro,observacao_email) values ('EMP-021','MARLON GOMES DA SILVA','marlon.gomes.da.silva@bsconta.com.br','BSconta+21','Auxiliar de Contabilidade','Contábil',NULL,'ATIVO',true,NULL,NULL,NULL,NULL,'{}'::text[],NULL,'Empregados.xls','E-mail não consta na planilha; valor provisório para funcionamento do protótipo.') on conflict (id) do update set nome=excluded.nome,email=excluded.email,codigo_colaborador=excluded.codigo_colaborador,cargo=excluded.cargo,departamento=excluded.departamento,admissao=excluded.admissao,status=excluded.status,email_provisorio=excluded.email_provisorio,horario_entrada=excluded.horario_entrada,horario_saida=excluded.horario_saida,intervalo_inicio=excluded.intervalo_inicio,intervalo_fim=excluded.intervalo_fim,dias_trabalho=excluded.dias_trabalho,horas_semanais=excluded.horas_semanais,fonte_cadastro=excluded.fonte_cadastro,observacao_email=excluded.observacao_email,updated_at=now();
insert into public.colaboradores_importacao (id,nome,email,codigo_colaborador,cargo,departamento,admissao,status,email_provisorio,horario_entrada,horario_saida,intervalo_inicio,intervalo_fim,dias_trabalho,horas_semanais,fonte_cadastro,observacao_email) values ('EMP-022','MIGUEL BRANDAO DE MELLO LEMOS','miguel.brandao.de.mello.lemos@bsconta.com.br','BSconta+22','Auxiliar Financeiro','Financeiro',NULL,'ATIVO',true,NULL,NULL,NULL,NULL,'{}'::text[],NULL,'Empregados.xls','E-mail não consta na planilha; valor provisório para funcionamento do protótipo.') on conflict (id) do update set nome=excluded.nome,email=excluded.email,codigo_colaborador=excluded.codigo_colaborador,cargo=excluded.cargo,departamento=excluded.departamento,admissao=excluded.admissao,status=excluded.status,email_provisorio=excluded.email_provisorio,horario_entrada=excluded.horario_entrada,horario_saida=excluded.horario_saida,intervalo_inicio=excluded.intervalo_inicio,intervalo_fim=excluded.intervalo_fim,dias_trabalho=excluded.dias_trabalho,horas_semanais=excluded.horas_semanais,fonte_cadastro=excluded.fonte_cadastro,observacao_email=excluded.observacao_email,updated_at=now();
insert into public.colaboradores_importacao (id,nome,email,codigo_colaborador,cargo,departamento,admissao,status,email_provisorio,horario_entrada,horario_saida,intervalo_inicio,intervalo_fim,dias_trabalho,horas_semanais,fonte_cadastro,observacao_email) values ('EMP-023','OTAVIO ABRAHAO RODRIGUES DA SILVA MEDEIROS','otavio.abrahao.rodrigues.da.silva.medeiros@bsconta.com.br','BSconta+23','Auxiliar Contabil','Contábil',NULL,'ATIVO',true,NULL,NULL,NULL,NULL,'{}'::text[],NULL,'Empregados.xls','E-mail não consta na planilha; valor provisório para funcionamento do protótipo.') on conflict (id) do update set nome=excluded.nome,email=excluded.email,codigo_colaborador=excluded.codigo_colaborador,cargo=excluded.cargo,departamento=excluded.departamento,admissao=excluded.admissao,status=excluded.status,email_provisorio=excluded.email_provisorio,horario_entrada=excluded.horario_entrada,horario_saida=excluded.horario_saida,intervalo_inicio=excluded.intervalo_inicio,intervalo_fim=excluded.intervalo_fim,dias_trabalho=excluded.dias_trabalho,horas_semanais=excluded.horas_semanais,fonte_cadastro=excluded.fonte_cadastro,observacao_email=excluded.observacao_email,updated_at=now();
insert into public.colaboradores_importacao (id,nome,email,codigo_colaborador,cargo,departamento,admissao,status,email_provisorio,horario_entrada,horario_saida,intervalo_inicio,intervalo_fim,dias_trabalho,horas_semanais,fonte_cadastro,observacao_email) values ('EMP-024','RAFAEL ITALO DE SOUZA FERNANDES','rafael.italo.de.souza.fernandes@bsconta.com.br','BSconta+24','Assistente Fiscal/Contábil III','Fiscal/Contábil',NULL,'ATIVO',true,NULL,NULL,NULL,NULL,'{}'::text[],NULL,'Empregados.xls','E-mail não consta na planilha; valor provisório para funcionamento do protótipo.') on conflict (id) do update set nome=excluded.nome,email=excluded.email,codigo_colaborador=excluded.codigo_colaborador,cargo=excluded.cargo,departamento=excluded.departamento,admissao=excluded.admissao,status=excluded.status,email_provisorio=excluded.email_provisorio,horario_entrada=excluded.horario_entrada,horario_saida=excluded.horario_saida,intervalo_inicio=excluded.intervalo_inicio,intervalo_fim=excluded.intervalo_fim,dias_trabalho=excluded.dias_trabalho,horas_semanais=excluded.horas_semanais,fonte_cadastro=excluded.fonte_cadastro,observacao_email=excluded.observacao_email,updated_at=now();
insert into public.colaboradores_importacao (id,nome,email,codigo_colaborador,cargo,departamento,admissao,status,email_provisorio,horario_entrada,horario_saida,intervalo_inicio,intervalo_fim,dias_trabalho,horas_semanais,fonte_cadastro,observacao_email) values ('EMP-025','ROSIANE DANIELLE DE ANDRADE FARIA','rosiane.danielle.de.andrade.faria@bsconta.com.br','BSconta+25','Auxiliar Fiscal/Contabil I','Fiscal/Contábil',NULL,'ATIVO',true,NULL,NULL,NULL,NULL,'{}'::text[],NULL,'Empregados.xls','E-mail não consta na planilha; valor provisório para funcionamento do protótipo.') on conflict (id) do update set nome=excluded.nome,email=excluded.email,codigo_colaborador=excluded.codigo_colaborador,cargo=excluded.cargo,departamento=excluded.departamento,admissao=excluded.admissao,status=excluded.status,email_provisorio=excluded.email_provisorio,horario_entrada=excluded.horario_entrada,horario_saida=excluded.horario_saida,intervalo_inicio=excluded.intervalo_inicio,intervalo_fim=excluded.intervalo_fim,dias_trabalho=excluded.dias_trabalho,horas_semanais=excluded.horas_semanais,fonte_cadastro=excluded.fonte_cadastro,observacao_email=excluded.observacao_email,updated_at=now();
insert into public.colaboradores_importacao (id,nome,email,codigo_colaborador,cargo,departamento,admissao,status,email_provisorio,horario_entrada,horario_saida,intervalo_inicio,intervalo_fim,dias_trabalho,horas_semanais,fonte_cadastro,observacao_email) values ('EMP-026','SHEILLA DANIELLE DE ANDRADE SILVA','sheilla.danielle.de.andrade.silva@bsconta.com.br','BSconta+26','Analista Fiscal','Fiscal',NULL,'ATIVO',true,NULL,NULL,NULL,NULL,'{}'::text[],NULL,'Empregados.xls','E-mail não consta na planilha; valor provisório para funcionamento do protótipo.') on conflict (id) do update set nome=excluded.nome,email=excluded.email,codigo_colaborador=excluded.codigo_colaborador,cargo=excluded.cargo,departamento=excluded.departamento,admissao=excluded.admissao,status=excluded.status,email_provisorio=excluded.email_provisorio,horario_entrada=excluded.horario_entrada,horario_saida=excluded.horario_saida,intervalo_inicio=excluded.intervalo_inicio,intervalo_fim=excluded.intervalo_fim,dias_trabalho=excluded.dias_trabalho,horas_semanais=excluded.horas_semanais,fonte_cadastro=excluded.fonte_cadastro,observacao_email=excluded.observacao_email,updated_at=now();

-- Quando os usuários forem provisionados no Supabase Auth, copie os dados da
-- tabela de importação para public.profiles usando o id de auth.users, mantendo
-- codigo_colaborador único.
